### ISSUE TITLE
Input box should have required attribute

### ISSUE THREAD

**Issue by coliff** [LeaVerou/issue-closing#2]
it'd be good if input was `required` so that you can't hit GO! without entering in a repo name first which results in a wasted API hit.

**Comment by LeaVerou** [comment]
Why would you hit go without entering a repo name? By accident?

**Comment by coliff** [comment]
unlikely to hit GO without a repo name by choice, but I was thinking any accidental hits or hits or bots/scripts could count towards the API limit so safer overall to have it `required`.

**Comment by LeaVerou** [comment]
I believe when unauthenticated the API limit is per IP, so if bots/script hit it, it's not a concern.

**Comment by coliff** [comment]
ok. Overall, I think experience is better if require attribute is used on inputs which are required but if you want to close without merging no problem :-)
