### ISSUE TITLE
Counterintuitive visualization

### ISSUE THREAD

**Issue by shaedrich** [LeaVerou/issue-closing#5]
The more red entries are in the table, the more green the right-hand pie chart gets and vice versa. I assume, this needs to be swapped, right?

**Comment by LeaVerou** [comment]
Sounds like it! Could you give me two examples so I could reproduce?

**Comment by shaedrich** [comment]
Sure thing! See below:

| [`github/explore`](https://projects.verou.me/issue-closing/?repo=github/explore) ([GitHub](https://github.com/github/explore)) | [`brianleroux/wtfjs`](https://projects.verou.me/issue-closing/?repo=brianleroux/wtfjs) ([GitHub](https://github.com/brianleroux/wtfjs)) |
| - | - |
| <ul><li><strong>short:</strong> 2</li><li><strong>long:</strong> 45</li><li><strong>Median:</strong> 1 day</strong></li><li><strong>Average:</strong> 4 days</strong></li><li><strong>Slowest:</strong> 2 months</strong></li><li><strong>Fastest:</strong> 13 seconds</strong></li></ul> | <ul><li><strong>short:</strong> 79</li><li><strong>long:</strong> 10</li><li><strong>Median:</strong> 1 year</strong></li><li><strong>Average:</strong> 1 year</strong></li><li><strong>Slowest:</strong> 7 years</strong></li><li><strong>Fastest:</strong> 32 seconds</strong></li></ul> |
| ![grafik](https://github.com/LeaVerou/issue-closing/assets/11225821/e137afaf-8f6b-49dc-b8f5-77ee84a40254) | ![grafik](https://github.com/LeaVerou/issue-closing/assets/11225821/5662f301-876e-42ea-9213-b8893e1785ed) |
| ![grafik](https://github.com/LeaVerou/issue-closing/assets/11225821/69425bfa-9236-49bf-9586-13c77edf0ed8) | ![grafik](https://github.com/LeaVerou/issue-closing/assets/11225821/0ddf8a3b-a978-408e-a848-21f98c9cb0bf) |

Does that work for you?

**Comment by LeaVerou** [comment]
Oh wow, that's pretty bad. Thank you!

**Comment by shaedrich** [comment]
You're welcome! But it looks like just a bit of CSS needs to be flipped.
